### ISSUE TITLE
ember build fails with ERR_INVALID_ARG_TYPE 

### ISSUE THREAD

**Issue by emmac3** [ember-bootstrap/ember-bootstrap#1439]
Hi here,

I'm running into an issue when running `ember s` after I installed the latest ember-bootstrap:

Once I took ember-bootstrap out of the package.json the build was successful again. Is there a compatibility issue with ember-cli 3.25.0 and the latest ember-bootstrap?
```- building...
node:internal/validators:164
      throw new ERR_INVALID_ARG_TYPE(name, 'Object', value);
      ^

TypeError [ERR_INVALID_ARG_TYPE]: The "options" argument must be of type object. Received an instance of Array
    at ChildProcess.target.send (node:internal/child_process:716:7)
    at Array.forEach (<anonymous>)
    at dispatchQueuedRequests (C:\Users\Emma\source\repos\lottapowder\node_modules\ember-raf-scheduler\node_modules\workerpool\lib\WorkerHandler.js:174:21)
    at ChildProcess.<anonymous> (C:\Users\Emma\source\repos\lottapowder\node_modules\ember-raf-scheduler\node_modules\workerpool\lib\WorkerHandler.js:129:7)
    at ChildProcess.emit (node:events:378:20)
    at ChildProcess.EventEmitter.emit (node:domain:470:12)
    at emit (node:internal/child_process:920:12)
    at processTicksAndRejections (node:internal/process/task_queues:82:21) {
  code: 'ERR_INVALID_ARG_TYPE'
}
```
---

Output from `ember bootstrap:info`:

```
Npm packages:
ember-bootstrap: ^4.6.3 -> 4.6.3
ember-cli: ~3.25.0 -> 3.25.0
bootstrap: ^4.6.0 -> 4.6.0
bootstrap-sass: n/a
ember-cli-sass: ^10.0.1 -> 10.0.1
ember-cli-less: n/a
Bower packages:
bootstrap: n/a
bootstrap-sass: n/a
ember-bootstrap configuration:
bootstrapVersion: 4
importBootstrapCSS: false
```

**Comment by simonihmig** [comment]
Hm, I don't really see how this could be related to ember-bootstrap. The error stack shows that `ember-raf-scheduler` is somehow involved, that we don't use here. 

Can you check why you have that dependency? ( `yarn why ember-raf-scheduler`, if you use yarn)

**Comment by emmac3** [comment]
seems like it's a dependency of ember-bootstrap@4.6.3

`npm ls ember-raf-scheduler
lottapowder@0.0.0 /Users/emmac/Square/repos/lottapowder
└─┬ ember-bootstrap@4.6.3
  └─┬ ember-popper@0.11.3
    └── ember-raf-scheduler@0.1.0`

**Comment by branan** [comment]
This appears to be https://github.com/ember-cli/ember-cli/issues/9404#issuecomment-792335093, which has a workaround patch that folks can apply.
