### ISSUE TITLE
tests errors since migrating qunit to 5.1.4

### ISSUE THREAD

**Issue by francispeixoto** [ember-bootstrap/ember-bootstrap#1611]
Since upgrading ember-qunit to 5.1.4 and following the migration guide. I get the attached errors in my tests which relate to ember-boostrap.

Has anyone run into this?

---

Output from `ember bootstrap:info`:

Npm packages:
ember-bootstrap: ^4.9.0 -> 4.9.0
ember-cli: ~3.28.0 -> 3.28.0
bootstrap: ^5.1.1 -> 5.1.1
bootstrap-sass: n/a
ember-cli-sass: n/a
ember-cli-less: n/a
Bower packages:
bootstrap: n/a
bootstrap-sass: n/a
ember-bootstrap configuration:
bootstrapVersion: 4
importBootstrapCSS: true

```
not ok 1 Chrome 93.0 - [28 ms] - Integration | Component | topnav: it renders
    ---
        actual: >
            null
        stack: >
            TypeError: Cannot read properties of null (reading 'classList')
                at Class.setup (http://localhost:7357/assets/vendor.js:32658:33)
                at Class.setupEventDispatcher (http://localhost:7357/assets/vendor.js:34232:18)
                at Class._bootSync (http://localhost:7357/assets/vendor.js:34156:14)
                at http://localhost:7357/assets/vendor.js:37668:77
                at initializePromise (webpack://__ember_auto_import__/./node_modules/ember-bootstrap/node_modules/rsvp/dist/rsvp.es.js?:172:240)
                at new Promise (webpack://__ember_auto_import__/./node_modules/ember-bootstrap/node_modules/rsvp/dist/rsvp.es.js?:437:298)
                at Class.boot (http://localhost:7357/assets/vendor.js:37668:27)
                at http://localhost:7357/assets/test-support.js:3826:65
                at tryCatcher (webpack://__ember_auto_import__/./node_modules/ember-bootstrap/node_modules/rsvp/dist/rsvp.es.js?:170:793)
                at invokeCallback (webpack://__ember_auto_import__/./node_modules/ember-bootstrap/node_modules/rsvp/dist/rsvp.es.js?:170:3997)
        message: >
            Promise rejected before "it renders": Cannot read properties of null (reading 'classList')
        negative: >
            false
        browser log: |
    ...
not ok 2 Chrome 93.0 - [15 ms] - Unit | Controller | application: it exists
    ---
        actual: >
            null
        stack: >
            TypeError: Cannot read properties of null (reading 'classList')
                at Class.setup (http://localhost:7357/assets/vendor.js:32658:33)
                at Class.setupEventDispatcher (http://localhost:7357/assets/vendor.js:34232:18)
                at Class._bootSync (http://localhost:7357/assets/vendor.js:34156:14)
                at http://localhost:7357/assets/vendor.js:37668:77
                at initializePromise (webpack://__ember_auto_import__/./node_modules/ember-bootstrap/node_modules/rsvp/dist/rsvp.es.js?:172:240)
                at new Promise (webpack://__ember_auto_import__/./node_modules/ember-bootstrap/node_modules/rsvp/dist/rsvp.es.js?:437:298)
                at Class.boot (http://localhost:7357/assets/vendor.js:37668:27)
                at http://localhost:7357/assets/test-support.js:3826:65
                at tryCatcher (webpack://__ember_auto_import__/./node_modules/ember-bootstrap/node_modules/rsvp/dist/rsvp.es.js?:170:793)
                at invokeCallback (webpack://__ember_auto_import__/./node_modules/ember-bootstrap/node_modules/rsvp/dist/rsvp.es.js?:170:3997)
        message: >
            Promise rejected before "it exists": Cannot read properties of null (reading 'classList')
        negative: >
            false
        browser log: |
    ...
not ok 3 Chrome 93.0 - [13 ms] - Unit | Route | application: it exists
    ---
        actual: >
            null
        stack: >
            TypeError: Cannot read properties of null (reading 'classList')
                at Class.setup (http://localhost:7357/assets/vendor.js:32658:33)
                at Class.setupEventDispatcher (http://localhost:7357/assets/vendor.js:34232:18)
                at Class._bootSync (http://localhost:7357/assets/vendor.js:34156:14)
                at http://localhost:7357/assets/vendor.js:37668:77
                at initializePromise (webpack://__ember_auto_import__/./node_modules/ember-bootstrap/node_modules/rsvp/dist/rsvp.es.js?:172:240)
                at new Promise (webpack://__ember_auto_import__/./node_modules/ember-bootstrap/node_modules/rsvp/dist/rsvp.es.js?:437:298)
                at Class.boot (http://localhost:7357/assets/vendor.js:37668:27)
                at http://localhost:7357/assets/test-support.js:3826:65
                at tryCatcher (webpack://__ember_auto_import__/./node_modules/ember-bootstrap/node_modules/rsvp/dist/rsvp.es.js?:170:793)
                at invokeCallback (webpack://__ember_auto_import__/./node_modules/ember-bootstrap/node_modules/rsvp/dist/rsvp.es.js?:170:3997)
        message: >
            Promise rejected before "it exists": Cannot read properties of null (reading 'classList')
        negative: >
            false
        browser log: |
    ...
not ok 4 Chrome 93.0 - [13 ms] - Unit | Route | contact: it exists
    ---
        actual: >
            null
        stack: >
            TypeError: Cannot read properties of null (reading 'classList')
                at Class.setup (http://localhost:7357/assets/vendor.js:32658:33)
                at Class.setupEventDispatcher (http://localhost:7357/assets/vendor.js:34232:18)
                at Class._bootSync (http://localhost:7357/assets/vendor.js:34156:14)
                at http://localhost:7357/assets/vendor.js:37668:77
                at initializePromise (webpack://__ember_auto_import__/./node_modules/ember-bootstrap/node_modules/rsvp/dist/rsvp.es.js?:172:240)
                at new Promise (webpack://__ember_auto_import__/./node_modules/ember-bootstrap/node_modules/rsvp/dist/rsvp.es.js?:437:298)
                at Class.boot (http://localhost:7357/assets/vendor.js:37668:27)
                at http://localhost:7357/assets/test-support.js:3826:65
                at tryCatcher (webpack://__ember_auto_import__/./node_modules/ember-bootstrap/node_modules/rsvp/dist/rsvp.es.js?:170:793)
                at invokeCallback (webpack://__ember_auto_import__/./node_modules/ember-bootstrap/node_modules/rsvp/dist/rsvp.es.js?:170:3997)
        message: >
            Promise rejected before "it exists": Cannot read properties of null (reading 'classList')
        negative: >
            false
        browser log: |
    ...
not ok 5 Chrome 93.0 - [13 ms] - Unit | Route | index: it exists
    ---
        actual: >
            null
        stack: >
            TypeError: Cannot read properties of null (reading 'classList')
                at Class.setup (http://localhost:7357/assets/vendor.js:32658:33)
                at Class.setupEventDispatcher (http://localhost:7357/assets/vendor.js:34232:18)
                at Class._bootSync (http://localhost:7357/assets/vendor.js:34156:14)
                at http://localhost:7357/assets/vendor.js:37668:77
                at initializePromise (webpack://__ember_auto_import__/./node_modules/ember-bootstrap/node_modules/rsvp/dist/rsvp.es.js?:172:240)
                at new Promise (webpack://__ember_auto_import__/./node_modules/ember-bootstrap/node_modules/rsvp/dist/rsvp.es.js?:437:298)
                at Class.boot (http://localhost:7357/assets/vendor.js:37668:27)
                at http://localhost:7357/assets/test-support.js:3826:65
                at tryCatcher (webpack://__ember_auto_import__/./node_modules/ember-bootstrap/node_modules/rsvp/dist/rsvp.es.js?:170:793)
                at invokeCallback (webpack://__ember_auto_import__/./node_modules/ember-bootstrap/node_modules/rsvp/dist/rsvp.es.js?:170:3997)
        message: >
            Promise rejected before "it exists": Cannot read properties of null (reading 'classList')
        negative: >
            false
        browser log: |
    ...
not ok 6 Chrome 93.0 - [13 ms] - Unit | Route | resume: it exists
    ---
        actual: >
            null
        stack: >
            TypeError: Cannot read properties of null (reading 'classList')
                at Class.setup (http://localhost:7357/assets/vendor.js:32658:33)
                at Class.setupEventDispatcher (http://localhost:7357/assets/vendor.js:34232:18)
                at Class._bootSync (http://localhost:7357/assets/vendor.js:34156:14)
                at http://localhost:7357/assets/vendor.js:37668:77
                at initializePromise (webpack://__ember_auto_import__/./node_modules/ember-bootstrap/node_modules/rsvp/dist/rsvp.es.js?:172:240)
                at new Promise (webpack://__ember_auto_import__/./node_modules/ember-bootstrap/node_modules/rsvp/dist/rsvp.es.js?:437:298)
                at Class.boot (http://localhost:7357/assets/vendor.js:37668:27)
                at http://localhost:7357/assets/test-support.js:3826:65
                at tryCatcher (webpack://__ember_auto_import__/./node_modules/ember-bootstrap/node_modules/rsvp/dist/rsvp.es.js?:170:793)
                at invokeCallback (webpack://__ember_auto_import__/./node_modules/ember-bootstrap/node_modules/rsvp/dist/rsvp.es.js?:170:3997)
        message: >
            Promise rejected before "it exists": Cannot read properties of null (reading 'classList')
        negative: >
            false
        browser log: |
    ...
```

**Comment by simonihmig** [comment]
I doubt this is related to ember-bootstrap. The stack trace does not contain actual ember-bootstrap code AFAICT, and `setupEventDispatcher` is in Ember core (`EventDispatcher` class). Also we already use latest ember-qunit in this addon, and in other apps w/ ember-bootstrap successfully, so I think the problem must lie elsewhere!

**Comment by jelhan** [comment]
@francispeixoto Did you solved this issue?

**Comment by brendaHuang-2023** [comment]
@jelhan Can you re-open this issue? I am seeing exactly the same error when I upgrade ember-qunit from 4.6.0 to 5.1.4.

**Comment by jelhan** [comment]
@brendaHuang-2023 Sure. But we need more information to debug it. As Simon mentioned it's unlikely that it's caused by Ember Bootstrap. Reproduction would be great.
