### ISSUE TITLE
Docs are not deployed

### ISSUE THREAD

**Issue by jelhan** [ember-bootstrap/ember-bootstrap#1855]
Docs build is broken once again. :sob: 

It seems that it is running into an endless loop. This is the first error, which seems to be relevant:

```
There was an error running your app in fastboot. More info about the error: 
 TypeError: Cannot read property 'getHelper' of undefined
    at ConstantsImpl.helper (/tmp/broccoli-2378Z4bSkT9Wfjss/out-446-broccoli_merge_trees/assets/vendor.js:49366:96)
    at resolveHelper (/tmp/broccoli-2378Z4bSkT9Wfjss/out-446-broccoli_merge_trees/assets/vendor.js:46160:22)
    at encodeOp (/tmp/broccoli-2378Z4bSkT9Wfjss/out-446-broccoli_merge_trees/assets/vendor.js:48590:18)
    at pushOp (/tmp/broccoli-2378Z4bSkT9Wfjss/out-446-broccoli_merge_trees/assets/vendor.js:48504:7)
    at /tmp/broccoli-2378Z4bSkT9Wfjss/out-446-broccoli_merge_trees/assets/vendor.js:46433:7
    at Compilers.compile (/tmp/broccoli-2378Z4bSkT9Wfjss/out-446-broccoli_merge_trees/assets/vendor.js:46408:7)
    at expr (/tmp/broccoli-2378Z4bSkT9Wfjss/out-446-broccoli_merge_trees/assets/vendor.js:46662:19)
    at CompilePositional (/tmp/broccoli-2378Z4bSkT9Wfjss/out-446-broccoli_merge_trees/assets/vendor.js:46749:7)
    at /tmp/broccoli-2378Z4bSkT9Wfjss/out-446-broccoli_merge_trees/assets/vendor.js:48404:17
    at Compilers.compile (/tmp/broccoli-2378Z4bSkT9Wfjss/out-446-broccoli_merge_trees/assets/vendor.js:46408:7)
    at compileStatements (/tmp/broccoli-2378Z4bSkT9Wfjss/out-446-broccoli_merge_trees/assets/vendor.js:48508:17)
    at maybeCompile (/tmp/broccoli-2378Z4bSkT9Wfjss/out-446-broccoli_merge_trees/assets/vendor.js:48483:18)
    at CompilableTemplateImpl.compile (/tmp/broccoli-2378Z4bSkT9Wfjss/out-446-broccoli_merge_trees/assets/vendor.js:48463:14)
    at Object.evaluate (/tmp/broccoli-2378Z4bSkT9Wfjss/out-446-broccoli_merge_trees/assets/vendor.js:53958:29)
    at AppendOpcodes.evaluate (/tmp/broccoli-2378Z4bSkT9Wfjss/out-446-broccoli_merge_trees/assets/vendor.js:51610:19)
    at LowLevelVM.evaluateSyscall (/tmp/broccoli-2378Z4bSkT9Wfjss/out-446-broccoli_merge_trees/assets/vendor.js:55530:22)
    at LowLevelVM.evaluateInner (/tmp/broccoli-2378Z4bSkT9Wfjss/out-446-broccoli_merge_trees/assets/vendor.js:55486:14)
    at LowLevelVM.evaluateOuter (/tmp/broccoli-2378Z4bSkT9Wfjss/out-446-broccoli_merge_trees/assets/vendor.js:55478:14)
    at VM.next (/tmp/broccoli-2378Z4bSkT9Wfjss/out-446-broccoli_merge_trees/assets/vendor.js:56489:24)
    at VM._execute (/tmp/broccoli-2378Z4bSkT9Wfjss/out-446-broccoli_merge_trees/assets/vendor.js:56473:23)
    at VM.execute (/tmp/broccoli-2378Z4bSkT9Wfjss/out-446-broccoli_merge_trees/assets/vendor.js:56464:21)
    at TemplateIteratorImpl.sync (/tmp/broccoli-2378Z4bSkT9Wfjss/out-446-broccoli_merge_trees/assets/vendor.js:56548:24)
    at RootState.render (/tmp/broccoli-2378Z4bSkT9Wfjss/out-446-broccoli_merge_trees/assets/vendor.js:10524:45)
    at /tmp/broccoli-2378Z4bSkT9Wfjss/out-446-broccoli_merge_trees/assets/vendor.js:10844:18
    at inTransaction (/tmp/broccoli-2378Z4bSkT9Wfjss/out-446-broccoli_merge_trees/assets/vendor.js:55372:9)
    at Renderer._renderRoots (/tmp/broccoli-2378Z4bSkT9Wfjss/out-446-broccoli_merge_trees/assets/vendor.js:10824:36)
    at Renderer._renderRootsTransaction (/tmp/broccoli-2378Z4bSkT9Wfjss/out-446-broccoli_merge_trees/assets/vendor.js:10876:14)
    at Renderer._renderRoot (/tmp/broccoli-2378Z4bSkT9Wfjss/out-446-broccoli_merge_trees/assets/vendor.js:10811:12)
    at Renderer._appendDefinition (/tmp/broccoli-2378Z4bSkT9Wfjss/out-446-broccoli_merge_trees/assets/vendor.js:10718:12)
    at Renderer.appendOutletView (/tmp/broccoli-2378Z4bSkT9Wfjss/out-446-broccoli_merge_trees/assets/vendor.js:10700:12)
    at invokeWithOnError (/tmp/broccoli-2378Z4bSkT9Wfjss/out-446-broccoli_merge_trees/assets/vendor.js:60708:18)
    at Queue.flush (/tmp/broccoli-2378Z4bSkT9Wfjss/out-446-broccoli_merge_trees/assets/vendor.js:60587:13)
    at DeferredActionQueues.flush (/tmp/broccoli-2378Z4bSkT9Wfjss/out-446-broccoli_merge_trees/assets/vendor.js:60793:21)
    at Backburner._end (/tmp/broccoli-2378Z4bSkT9Wfjss/out-446-broccoli_merge_trees/assets/vendor.js:61345:34)
    at Backburner._boundAutorunEnd (/tmp/broccoli-2378Z4bSkT9Wfjss/out-446-broccoli_merge_trees/assets/vendor.js:60994:14)
```

CI is terminated with a `MaxBufferError` after some time. See this CI pipeline for details: https://github.com/ember-bootstrap/ember-bootstrap/actions/runs/3962402891/jobs/6789111505

I can reproduce the error locally if running `ember build --prod` in `docs/`.

The error seems to impact only the production build. I don't see the error if doing a development build (`ember build`) of the docs app locally.

**Comment by jelhan** [comment]
I was able tracing it down to `/components/accordion` route. Build is passing locally with this minor change:

```
diff --git a/docs/ember-cli-build.js b/docs/ember-cli-build.js
index d5174169..1658f88a 100644
--- a/docs/ember-cli-build.js
+++ b/docs/ember-cli-build.js
@@ -16,7 +16,7 @@ module.exports = function (defaults) {
       urls: [
         '/',
         '/components',
-        '/components/accordion',
+        // '/components/accordion',
         '/components/alert',
         '/components/button',
         '/components/button-group',
```

**Comment by jelhan** [comment]
At least in this case it was an actual bug in the addon and not only in its documentation. See #1856 for details.
