### ISSUE TITLE
CI fails for recent Chrome

### ISSUE THREAD

**Issue by jelhan** [ember-bootstrap/ember-bootstrap#1953]
CI started to fail for recent Chrome:

```
not ok 528 Chrome 117.0 - [87 ms] - Integration | Component | bs-tooltip: should position tooltip arrow centered
    ---
        actual: >
            false
        expected: >
            true
        stack: >
                at Object.<anonymous> (http://localhost:7357/assets/chunk.ea411c337862538e1672.js:15848:12)
        message: >
            Expected position: 100, actual: 94
        negative: >
            false
        browser log: |
    ...
not ok 529 Chrome 117.0 - [81 ms] - Integration | Component | bs-tooltip: should adjust tooltip arrow
    ---
        actual: >
            false
        expected: >
            true
        stack: >
                at Object.<anonymous> (http://localhost:7357/assets/chunk.ea411c337862538e1672.js:15875:12)
        message: >
            Expected position: 156, actual: 144
        negative: >
            false
        browser log: |
    ...
```

But I only see this error in GitHub Workflows. Locally it is passing with expected values. Need to investigate why. Using the same Chrome version locally as reported to be used in CI.

This is blocking any change to get it.

**Comment by jelhan** [comment]
I just noticed that the default test is working fine. The default test uses Bootstrap 5 as well. Maybe the Ember Try scenarios are not actually using Bootstrap 5? :thinking:

**Comment by jelhan** [comment]
Bootstrap is pinned to 5.2.3 in `package.json`. But when running with Ember Try it is set to `^5.0.0`. It seems that a newer Bootstrap version is causing the change.
